//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWniosek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osoba
    {
        public string Id { get; set; }
        public string Nazwisko_i_Imie { get; set; }
        public long PESEL { get; set; }
        public string Stanowisko { get; set; }
        public string Komorka { get; set; }
    }
}
